// <auto-generated />
using System;
using CSVParser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSVParser.Migrations
{
    [DbContext(typeof(CSVParserDbContext))]
    [Migration("20241227193420_AllowNullablePassengerCount")]
    partial class AllowNullablePassengerCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSVParser.Data.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DOLocationID")
                        .HasColumnType("int")
                        .HasColumnName("DOLocationID");

                    b.Property<DateTime>("DropoffDatetime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PULocationID")
                        .HasColumnType("int")
                        .HasColumnName("PULocationID");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickupDatetime")
                        .HasColumnType("datetime");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<double>("TripDistance")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__Trips__3214EC07160D6911");

                    b.HasIndex(new[] { "PULocationID" }, "IX_Trips_PULocationID");

                    b.HasIndex(new[] { "PickupDatetime", "DropoffDatetime" }, "IX_Trips_PickupDropoff");

                    b.HasIndex(new[] { "TripDistance" }, "IX_Trips_TripDistance")
                        .IsDescending();

                    b.HasIndex(new[] { "PickupDatetime", "DropoffDatetime", "PassengerCount" }, "IX_Trips_Unique")
                        .IsUnique()
                        .HasFilter("([PassengerCount] IS NOT NULL)");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
